import jsPDF from 'jspdf';

/**
 * Export clinical note as PDF
 * @param {Object} note - Clinical note object with chief_complaint, history, etc.
 * @param {Object} patient - Patient info (firstName, lastName, age, gender)
 * @param {string} transcript - Full conversation transcript
 */
export function exportNoteAsPDF(note, patient = {}, transcript = '') {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    let yPosition = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const maxWidth = pageWidth - 2 * margin;
    const lineHeight = 7;

    // Helper function to add text and handle page breaks
    function addText(text, fontSize, isBold = false, isTitle = false) {
      doc.setFontSize(fontSize);
      doc.setFont('helvetica', isBold ? 'bold' : 'normal');

      if (isTitle) {
        doc.setTextColor(33, 150, 243); // Blue
      } else {
        doc.setTextColor(0, 0, 0);
      }

      const lines = doc.splitTextToSize(text, maxWidth);
      const textHeight = lines.length * (fontSize * 0.35);

      // Check if we need a new page
      if (yPosition + textHeight + 5 > pageHeight - 10) {
        doc.addPage();
        yPosition = margin;
      }

      doc.text(lines, margin, yPosition);
      yPosition += textHeight + 3;
    }

    // Title
    addText('Clinical Consultation Note', 16, true, true);
    yPosition += 2;

    // Patient Info
    if (patient.firstName || patient.lastName) {
      addText(
        `Patient: ${patient.firstName || ''} ${patient.lastName || ''}${patient.age ? ' | Age: ' + patient.age : ''}${patient.gender ? ' | ' + patient.gender : ''}`,
        11,
        false
      );
    }

    // Date
    addText(`Date: ${new Date().toLocaleDateString('en-IN')}`, 11, false);
    yPosition += 3;

    // Add horizontal line
    doc.setDrawColor(200);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 5;

    // Chief Complaint
    if (note.chief_complaint) {
      addText('Chief Complaint', 12, true);
      addText(note.chief_complaint, 10);
      yPosition += 2;
    }

    // History
    if (note.history) {
      addText('History of Present Illness', 12, true);
      addText(note.history, 10);
      yPosition += 2;
    }

    // Examination
    if (note.examination) {
      addText('Physical Examination', 12, true);
      addText(note.examination, 10);
      yPosition += 2;
    }

    // Diagnosis
    if (note.diagnosis) {
      addText('Assessment / Diagnosis', 12, true);
      addText(note.diagnosis, 10);
      yPosition += 2;
    }

    // Prescription
    const prescriptionArray = Array.isArray(note.prescription) ? note.prescription : [];
    if (prescriptionArray.length > 0) {
      addText('Prescription', 12, true);
      prescriptionArray.forEach((med) => {
        if (med && typeof med === 'object') {
          const medText = `• ${med.drug || 'Unknown'}${med.dose ? ' - ' + med.dose : ''}${med.frequency ? ' (' + med.frequency + ')' : ''}`;
          addText(medText, 10);
        } else if (typeof med === 'string') {
          addText(`• ${med}`, 10);
        }
      });
      yPosition += 2;
    }

    // Follow-up
    if (note.followup) {
      addText('Follow-up Instructions', 12, true);
      addText(note.followup, 10);
      yPosition += 2;
    }

    // Transcript section (if provided)
    if (transcript) {
      doc.addPage();
      yPosition = margin;

      addText('Consultation Transcript', 12, true);
      yPosition += 2;
      addText(transcript, 9);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      'Generated by Scribologist - Clinical Scribe AI',
      margin,
      pageHeight - 10
    );

    // Save PDF
    const fileName = `Clinical_Note_${patient.firstName || 'Patient'}_${new Date().getTime()}.pdf`;
    doc.save(fileName);
    
    return { success: true };
  } catch (error) {
    console.error('Failed to export PDF:', error);
    return { success: false, error };
  }
}

/**
 * Copy note to clipboard as formatted text
 */
export async function copyNoteToClipboard(note, patient = {}) {
  try {
    let text = 'CLINICAL CONSULTATION NOTE\n';
    text += '='.repeat(50) + '\n\n';

    if (patient.firstName || patient.lastName) {
      text += `Patient: ${patient.firstName || ''} ${patient.lastName || ''}\n`;
      if (patient.age) text += `Age: ${patient.age}\n`;
      if (patient.gender) text += `Gender: ${patient.gender}\n`;
    }

    text += `Date: ${new Date().toLocaleDateString('en-IN')}\n\n`;
    text += '='.repeat(50) + '\n\n';

    if (note.chief_complaint) {
      text += `CHIEF COMPLAINT:\n${note.chief_complaint}\n\n`;
    }

    if (note.history) {
      text += `HISTORY:\n${note.history}\n\n`;
    }

    if (note.examination) {
      text += `EXAMINATION:\n${note.examination}\n\n`;
    }

    if (note.diagnosis) {
      text += `DIAGNOSIS:\n${note.diagnosis}\n\n`;
    }

    const prescriptionArray = Array.isArray(note.prescription) ? note.prescription : [];
    if (prescriptionArray.length > 0) {
      text += `PRESCRIPTION:\n`;
      prescriptionArray.forEach((med) => {
        if (med && typeof med === 'object') {
          text += `• ${med.drug || 'Unknown'}${med.dose ? ' - ' + med.dose : ''}${med.frequency ? ' (' + med.frequency + ')' : ''}\n`;
        } else if (typeof med === 'string') {
          text += `• ${med}\n`;
        }
      });
      text += '\n';
    }

    if (note.followup) {
      text += `FOLLOW-UP:\n${note.followup}\n`;
    }

    await navigator.clipboard.writeText(text);
    return { success: true };
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    // Fallback: try using the old method
    try {
      const textArea = document.createElement('textarea');
      textArea.value = text;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      return { success: true };
    } catch (fallbackError) {
      console.error('Fallback copy method also failed:', fallbackError);
      return { success: false, error: fallbackError };
    }
  }
}
